#!/usr/bin/env sh
set -eu

die() {
	echo "error:" "$@" >&2
	exit 2
}

[ ! -z "${1-}" ] || die "do not run directly - this build script should be a part of a shebang"
[ ! -z "${2-}" ] || die "usage: ${1-} <bin_dir>"

THIS_SCRIPT="${0}"
BUILD_SCRIPT="${1}"
ROOT_DIR="$(dirname "${0}")/oro-build"
BOOTSTRAP_SCRIPT="$ROOT_DIR/oro-build.lua"
BIN_DIR="${2}"

shift 2

if [ ! -d "$BIN_DIR" ]; then
	mkdir -p "$BIN_DIR" || die "failed to create build directory: ${BIN_DIR}"
fi

if [ ! -f "$BIN_DIR/.oro-build" ] || test "$ROOT_DIR/oro-build.c" -nt "$BIN_DIR/.oro-build" ; then
	CC="${CC-cc}"

	"${CC}" --version >/dev/null ||\
		die "either \$CC not set, or it/'cc' (the default) does not refer to a valid program"

	echo 'first run detected; bootstrapping Oro build...'

	"${CC}" -o "$BIN_DIR/.oro-build" -O3 -g0 -DMAKE_LIB=1 -DLUA_ANSI=1 -I"$ROOT_DIR/ext/lua" "$ROOT_DIR/ext/lua/onelua.c" "$ROOT_DIR/ext/luafilesystem/src/lfs.c" "$ROOT_DIR/oro-build.c" -lm
fi

"${BIN_DIR}/.oro-build" "$ROOT_DIR" "$BIN_DIR" "$BOOTSTRAP_SCRIPT" "$BUILD_SCRIPT" "$@"
# vim: set syntax=sh:
