name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run tests
      run: |
        cd oro-build/test
        ./run.sh
